### ISSUE TITLE
[FR] Provide ROMs based on Linux Surface kernel and tools

### ISSUE THREAD

**Issue by KAMiKAZOW** [BlissRoms-x86/bug_reports#10]
The Linux Surface project offers currently the best experience for Surface devices. Would be cool if not only "regular" desktop Linux distributions could benefit from it but also BlissOS. Just an hour ago they've announced an IPTS daemon as a replacement for the older in-kernel driver.

Links:

The Linux Surface project: https://github.com/linux-surface/linux-surface/

Their announcements: https://github.com/linux-surface/linux-surface/issues/96

**Comment by hmtheboy154** [comment]
linux-surface is something I've been experiemented for a while now. I'll make some build that include it soon
