### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tylros** [BlissRoms-x86/bug_reports#2]
**Steps To Reproduce**

1. The instaĺlation completes successfully
2. And they you try to boot bliss os 12...it starts displaying the bliss logo and then the pc shuts down.

**Expected behavior**

**Screenshots**

**Device:**
Hp Elitebook 820 g1
Core i5
Intel hd graphics
8gb Ram

**Additional information**

**Comment by hmtheboy154** [comment]
https://github.com/BlissRoms-x86/bug_reports/issues/3#issuecomment-1254375724
