### ISSUE TITLE
[BUG] SystemUI crashes on unlocking (Bliss OS 12 Yantra)

### ISSUE THREAD

**Issue by hacker1024** [BlissRoms-x86/bug_reports#3]
When I first boot the latest Bliss OS 12 build on my Microsoft SP3, SystemUI crashes and returns to a lock screen. It repeats when I swipe up, with the same stacktrace.

**Steps To Reproduce**

1. Install the OS
2. Unlock the lock screen

**Expected behavior**

It shouldn't crash

**BlissRoms source:**

Probably the file mentioned on this line
```
at com.android.systemui.statusbar.policy.KeyButtonDrawable.draw(KeyButtonDrawable.java:271)
```

**Device:**

 - Microsoft Surface Pro 3
 - Build date (ex. 20200204): 20200327

**Additional information**

Here's a stack trace: https://pastebin.com/raw/X4gzns6c

I suspect [Rescue Party](https://source.android.com/devices/tech/debug/rescue-party) comes into play and causes #2.

**Comment by hmtheboy154** [comment]
BlissOS 12 will be unmaintained.
