### ISSUE TITLE
[BUG] Can't boot to android

### ISSUE THREAD

**Issue by Xeonic-Saturn** [BlissRoms-x86/bug_reports#5]
**Steps To Reproduce**

1. Download Bliss-OS-Merkaba-v12.6-android_x86_64-OFFICIAL-202005041401_k-k5.6.2-si-yling-rmi_m-10.0.8-ax86_ld-2.4.100-ax86-ma_dg-_dh-_mg-_gms_cros-hd_cros-wv and install it
2. Reboot the computer and set to boot on the android that already installed
3. Enter Android x86 and wait the boot animation
4. Congrats, the laptop shuted down

**Expected behavior**

I think it normal on the first time booting and the laptop will turn on again automaticly, but it didn't.

**Screenshots**

**BlissRoms source:**

 - Link to last merged Gerrit commit: https://sourceforge.net/projects/blissos-dev/files/merkaba/Bliss-OS-Merkaba-v12.6-android_x86_64-OFFICIAL-202005041401_k-k5.6.2-si-yling-rmi_m-10.0.8-ax86_ld-2.4.100-ax86-ma_dg-_dh-_mg-_gms_cros-hd_cros-wv.iso/download

**Device:**

 - Codename (ex. bullhead):  ASUS Vivobook Flip 14 TP410UA 
 - Spec : Intel core i3-7100 U, 2.4 GHz, 4 GB DDR4 RAM, and
![Screen Capture_deepin-devicemanager_20200523220919](https://user-images.githubusercontent.com/65819954/82734019-33c25e80-9d42-11ea-9bb7-754ea73e3dae.png)

**Additional information**

**Comment by hmtheboy154** [comment]
https://github.com/BlissRoms-x86/bug_reports/issues/3#issuecomment-1254375724
