### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jonathannpayne** [BlissRoms-x86/bug_reports#6]
On a kodlis gn41 and minis forum GN31 mini pc bliss os 12 will not boot past the logo, just hangs.

**Steps To Reproduce**

run live form usb and installed to a partion

1. 
2. 

**Expected behavior**

**Screenshots**

**BlissRoms source:**

 - Link to last merged Gerrit commit: 

**Device:**

 - Codename (ex. bullhead):  
 - Build date (ex. 20200204): 

**Additional information**

**Comment by hmtheboy154** [comment]
https://github.com/BlissRoms-x86/bug_reports/issues/3#issuecomment-1254375724
