### ISSUE TITLE
[BUG] Wifi doesn't get enabled

### ISSUE THREAD

**Issue by mimminou** [BlissRoms-x86/bug_reports#9]
Trying to enable wifi after waking pc from sleep does not enable it, it's just stuck on trying to enable wifi, rebooting doesn't solve the issue either

**Steps To Reproduce**
1.  Make pc go to sleep
2.  leave sleep and power up the pc, Wifi won't work

**Expected behavior**
Wifi gets enabled . . .

**Device:**
 - Device : Lenovo Thinkpad Yoga X1 3rd Gen 

 - Build date (ex. 20200204):  Bliss 11.10 - 20200411

**Additional Info:**
Wireless card is : Intel Dual-Band Wireless AC 8265

**Comment by saschakr** [comment]
I have the same Issue using a Acer Aspire P3 (Tablet) using BlissOS 11.10

Are there any logs I could provide?

**Comment by mimminou** [comment]
> I have the same Issue using a Acer Aspire P3 (Tablet) using BlissOS 11.10
> 
> Are there any logs I could provide?

i've had a similar experience with custom roms on my old phones back when kitkat was released, it's extremly likely that it's a Kernel issue and there is nothing we can do (aside from factory reset / reinstalling ) except wait for devs to fix it, Kernel logs might help but that's just a guess.

**Comment by hmtheboy154** [comment]
11.10 is old. I myself have an Thinkpad X1 Yoga Gen 3 and the 8265 card does work on newer builds
